// <auto-generated />
namespace Test.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class x2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(x2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051522313_x2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
